### ISSUE TITLE
OAuth parameter deprecation notice

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site-api#81] opened 2020-02-04 08:39 UTC
Got an email from GitHub a few hours ago:

> Hello there!
> 
> On February 3rd, 2020 at 22:03 (UTC) your application (PluginSite) used its `client_id` and `client_secret` (with the User-Agent Apache-HttpClient/4.5.2 (Java/1.8.0_212)) as part of a set of query parameters to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/114257225/readme
> 
> Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder at most once every 3 days.
Just one URL that was accessed with a User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
The GitHub Team

**Comment by timja** [comment] 2020-02-04 08:59
thanks @daniel-beck, I've transferred it to the plugin-site-api as it's here that does the GitHub work, the code around here needs updating:

https://github.com/jenkins-infra/plugin-site-api/blob/bd2a5fe337ddf9526666ef5a7ad6a3f5bb388c6f/src/main/java/io/jenkins/plugins/services/impl/GithubExtractor.java#L24

**Comment by daniel-beck** [comment] 2020-07-25 21:55
> Hello there!
> 
> On July 5th, 2020 at 22:36 (UTC) your application (PluginSite) used its `client_id` and `client_secret` (with the User-Agent Apache-HttpClient/4.5.2 (Java/1.8.0_212)) as part of a set of query parameters to access an endpoint through the GitHub API:
> 
> https://api.github.com/repositories/1163573/releases
> 
> Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

This is getting worse?! `/releases` is a brand new feature…? @halkeye ?

**Comment by halkeye** [comment] 2020-07-26 02:24
releases is just using the same key that the rest of the code is using.

If infra adds a new secret, i can probably update the code real quick.

**Comment by timja** [comment] 2020-07-26 06:19
The issue is that it’s using query parameters for auth isn’t it? Shouldn’t need a new secret?

**Comment by halkeye** [comment] 2020-07-26 06:26
Oh I thought we needed to switch to an access token with bearer auth. Didn't realize client Id and secret could be basic username password auth. I'll try and swap it tomorrow

**Closed** 2020-07-26 22:38 UTC
